image: node:16-bullseye

stages:
  - deploy

deploy-job:
  stage: deploy
  only:
      - staging
  before_script:
    - apt update
    - apt install openssh-client zip unzip -y
    - zip -r admin_tsai.zip .
    - chmod 700 ci/react.pem
    - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
    - ssh-keyscan 18.205.5.49 >> ~/.ssh/known_hosts
  script:
    - scp -i ci/react.pem admin_tsai.zip ubuntu@18.205.5.49:/home/ubuntu/TSAI_DEV
    - ssh -i ci/react.pem ubuntu@18.205.5.49 "cd TSAI_DEV && unzip -o admin_tsai.zip -d admin_tsai && cd admin_tsai && pm2 stop DEV && pm2 delete DEV && yarn && pm2 start "yarn start" --name DEV"
