image: node:16-bullseye

stages:         
  - deploy

deploy-job:
  stage: deploy
  before_script:
    - apt update
    - apt install openssh-client zip unzip -y
    - zip -r upload.zip .
    - chmod 700 ci/react.pem
    - mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
    - ssh-keyscan 18.205.5.49 >> ~/.ssh/known_hosts
  script:
    - scp -i ci/react.pem upload.zip ubuntu@18.205.5.49:/home/ubuntu/
    - ssh -i ci/react.pem ubuntu@18.205.5.49 "unzip upload.zip && pm2 start yarn --interpreter bash --name  given-name -- start"
